// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveTextFile(arg1:string,arg2:string):Promise<void>;

export function SelectFolderAndListFiles():Promise<Array<main.FileInfo>>;
