// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetLastSavedDir():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ReadFile(arg1:string):Promise<main.FileData>;

export function SaveTextFile(arg1:string,arg2:string):Promise<void>;

export function SelectFolderAndListFiles(arg1:boolean):Promise<Array<main.FileInfo>>;

export function UpdateLastDir(arg1:string):Promise<void>;
